{{- $apiBaseUrl := trimSuffix "/" (.Values.apiBaseUrl | default "http://api.yas.local.com") -}}
{{- $defaultUrls := printf "[{ url: '%s/product/v3/api-docs', name: 'Product' }, { url: '%s/media/v3/api-docs', name: 'Media' }, { url: '%s/customer/v3/api-docs', name: 'Customer' }, { url: '%s/cart/v3/api-docs', name: 'Cart'}, { url: '%s/order/v3/api-docs', name: 'Order'}, { url: '%s/inventory/v3/api-docs', name: 'Inventory'}, { url: '%s/tax/v3/api-docs', name: 'Tax' }, { url: '%s/search/v3/api-docs', name: 'Search'}, { url: '%s/sampledata/v3/api-docs', name: 'Sample Data'}]" $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl $apiBaseUrl -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger-ui.fullname" . }}
  labels:
    {{- include "swagger-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "swagger-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swagger-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASE_URL
              value: {{ .Values.baseUrl }}
            - name: URLS
              value: {{ (.Values.urls | default $defaultUrls) | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.baseUrl }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.baseUrl }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
