backend:
  image:
    repository: thaithienphu/customer
    tag: latest

  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /customer
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml
