{{- if .Values.legacyAlias.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.legacyAlias.name }}
  labels:
    app.kubernetes.io/name: storefront-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: storefront-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
