backend:
  image:
    repository: thaithienphu/inventory
    tag: latest

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
    host: api.staging.yas.local.com
    path: /inventory
