# App of Apps: app mẹ quản lý tất cả service con
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tthphat/yas-gitops.git
    targetRevision: main
    # Trỏ vào thư mục chứa các file Application YAML của từng service
    path: k8s/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
