backend:
  image:
    repository: thaithienphu/search
    tag: 7c2bba4

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
    # --- THÊM 4 DÒNG DƯỚI ĐÂY VÀO ĐÂY ---
    # - name: SPRING_ELASTICSEARCH_URIS
    #   value: "https://elasticsearch-es-http.elasticsearch:9200"
    # - name: SPRING_ELASTICSEARCH_USERNAME
    #   value: "elastic"
    # - name: SPRING_ELASTICSEARCH_PASSWORD
    #   value: evBF1lnbtUeDFMrXbbINnGKb
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /search
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
