apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-order                  # Tên của App hiển thị trên ArgoCD
  namespace: argocd                # Nơi chứa bộ não ArgoCD (mặc định thường là namespace argocd)
spec:
  project: default                 # Project quản lý
  source:
    repoURL: 'https://github.com/tthphat/yas-gitops.git' # Repo Git chứa code hạ tầng của bạn
    targetRevision: main           # Branch chạy chính
    path: k8s/charts/order

  destination:
    server: 'https://kubernetes.default.svc' # Cụm K8s đích (in-cluster)
    namespace: yas                 # Namespace đích nơi Pod thực tế sẽ mọc lên (yas)
  
  # Cấu hình đồng bộ
  syncPolicy:
    automated:                     # Nếu muốn tự động đồng bộ khi Git thay đổi thì bật cái này
      prune: true                  # Tự động dọn rác cấu hình cũ
      selfHeal: true               # Tự động sửa lỗi nếu ai đó sửa bậy dưới cụm K8s