# Loại resource của ArgoCD - dùng để khai báo 1 application
apiVersion: argoproj.io/v1alpha1
kind: Application 
# - Nói cho Kubernetes biết: "Đây là một ArgoCD Application, đừng nhầm với Deployment hay Service"
# - Nếu viết kind: Deployment → K8s tạo Pod. Nếu kind: Application → ArgoCD nhận lấy và deploy Helm chart
metadata:
  # Tên app hiển thị trên ArgoCD UI
  name: product
  # ArgoCD được cài trong namespace argocd
  namespace: argocd
spec:
  # Project mặc định, có thể tạo project riêng để phân quyền
  project: default
  source:
    # GitOps repo chứa Helm chart
    repoURL: git@github.com:tthphat/yas-gitops.git
    # Branch nào được deploy
    targetRevision: main
    # Đường dẫn đến Helm chart của service product
    path: k8s/charts/product
    # Cấu hình Helm
    helm:
      # Tự động build dependency (helm dependency build) trước khi deploy
      buildDependencies: true
  destination:
    # Cluster mặc định (chính là cluster đang chạy ArgoCD)
    server: https://kubernetes.default.svc
    # Namespace đích nơi Pod thực tế sẽ mọc lên (yas)
    namespace: yas
  syncPolicy:
    automated:
      # prune: xoá resource cũ nếu không còn trong Git
      prune: true
      # selfHeal: nếu ai đó sửa resource bằng tay, ArgoCD tự động gán lại về đúng Git
      selfHeal: true
