backend:
  image:
    repository: thaithienphu/product
    tag: v1.0.1

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
  ingress:
    enabled: true
    host: api.staging.yas.local.com
    path: /product
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
