backend:
  image:
    repository: thaithienphu/cart
    tag: v1.0.1

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
  ingress:
    enabled: true
    host: api.staging.yas.local.com
    path: /cart
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
