backend:
  image:
    repository: thaithienphu/sampledata
    tag: 7c2bba4

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /sampledata
  extraVolumes:
    - name: sampledata-application
      configMap:
        name: sampledata-application-configmap
  extraVolumeMounts:
    - name: sampledata-application
      mountPath: /opt/yas/sampledata
  extraApplicationConfigPaths:
    - /opt/yas/sampledata/sampledata-application.yaml
