backend:
  image:
    repository: thaithienphu/tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: true
    host: api.staging.yas.local.com
    path: /tax
