backend:
  image:
    repository: thaithienphu/tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
  ingress:
    enabled: true
    host: api.staging.yas.local.com
    path: /tax
